# BoardConfig.mk for Zeblaze Thor 5 Pro (TWRP) - 32-bit configuration

# Platform
TARGET_BOARD_PLATFORM := mt6739
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := mt6739

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_SMP := true

# Kernel
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x04f88000 --second_offset 0x00e88000 --tags_offset 0x03f88000

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824 # 24MB
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824 # 24MB
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560 # 2.5GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 34359738368 # 32GB
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832 # 432MB
BOARD_FLASH_BLOCK_SIZE := 131072 # 128KB

# File systems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Recovery
TARGET_RECOVERY_FSTAB := device/zeblaze/thor5pro/recovery.fstab

# TWRP Configuration
TW_THEME := watch_mdpi
TW_ROUND_SCREEN := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_INCLUDE_NTFS_3G := true
TW_NO_EXFAT_FUSE := true
TW_EXCLUDE_SUPERSU := true
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_TOOLBOX := true

# Display
TARGET_SCREEN_WIDTH := 320
TARGET_SCREEN_HEIGHT := 320

# Misc TWRP Configurations
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_RESETPROP := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

# Debug flags
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# 32-bit specific
TARGET_USES_32_BIT_BINDER := true
